WRAP_CLASS("itk::ColocalizationImageFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(s ${WRAP_ITK_SCALAR})
      FOREACH(i ${WRAP_ITK_INT})
        WRAP_TEMPLATE("${ITKM_I${s}${d}}${ITKM_I${i}${d}}${ITKM_I${s}2}" "${ITKT_I${s}${d}}, ${ITKT_I${i}${d}}, ${ITKT_I${s}2}")
      ENDFOREACH(i)
    ENDFOREACH(s)
  ENDFOREACH(d)
END_WRAP_CLASS()
